// Run the script with:
// tsc 20230918-englishLinks.ts && node ./20230918-englishLinks.js

import { readFileSync, writeFileSync } from "fs"
import { join } from "path"

import * as glob from "glob"

const contentPath = join(__dirname, "../../content")

type PathPair = [sourcePath: string, targetPath: string]

const replacePathsInFiles = (pathPair: PathPair) => {
  const [sourcePath, targetPath] = pathPair

  glob("**/*.md", { cwd: contentPath }, (err, files) => {
    if (err) {
      console.error("Error while reading files:", err)
      return
    }

    files.forEach((file) => {
      const path = join(contentPath, file)
      let fileContent = readFileSync(path, "utf-8")
      const regex = new RegExp(`\\(${sourcePath}(#|\\))`, "g")
      fileContent = fileContent.replace(regex, `(${targetPath}$1`)
      writeFileSync(path, fileContent, "utf-8")
    })
  })
}

// eslint-disable-next-line max-len
// prettier-ignore
const pathPairs: Array<PathPair> = [
  ["/blog/sos-soiree", "/blog/20230706-sos-soiree"],
  ["/blog/transition-numerique-post-covid", "/blog/20211113-transition-numerique-post-covid"],
  ["/blog/911-delicious-pizza", "/blog/20210910-911-delicious-pizza"],
  ["/apps/0test/connexion-hubrise", "/apps/0test/connect-hubrise"],
  ["/apps/adipos/plateformes-livraison-repas", "/apps/adipos/food-delivery-platforms"],
  ["/apps/carre-pos/connexion-hubrise", "/apps/carre-pos/connect-hubrise"],
  ["/apps/carre-pos/associer-codes-ref", "/apps/carre-pos/map-ref-codes"],
  ["/apps/carre-pos/envoyer-catalogue", "/apps/carre-pos/push-catalog"],
  ["/apps/carre-pos/envoyer-inventaire", "/apps/carre-pos/push-inventory"],
  ["/apps/carre-pos/recevoir-commandes", "/apps/carre-pos/receive-orders"],
  ["/apps/carre-pos/envoyer-commandes", "/apps/carre-pos/send-orders"],
  ["/apps/carre-pos/terminologie", "/apps/carre-pos/terminology"],
  ["/apps/catalog-manager/faqs/populate-catalog-from-other-app", "/apps/catalog-manager/faqs/populate-catalog-from-another-app"],
  ["/apps/coursicab/connexion-hubrise", "/apps/coursicab/connect-hubrise"],
  ["/apps/coursicab/interface-utilisateur", "/apps/coursicab/user-interface"],
  ["/apps/deliveroo/connexion-hubrise", "/apps/deliveroo/connect-hubrise"],
  ["/apps/deliveroo/associer-codes-ref", "/apps/deliveroo/map-ref-codes"],
  ["/apps/deliveroo/recuperer-catalogue", "/apps/deliveroo/pull-catalog"],
  ["/apps/deliveroo/envoi-catalogue", "/apps/deliveroo/push-catalog"],
  ["/apps/deliveroo/recevoir-commandes", "/apps/deliveroo/receive-orders"],
  ["/apps/deliveroo/terminologie", "/apps/deliveroo/terminology"],
  ["/apps/deliveroo/depannage", "/apps/deliveroo/troubleshooting"],
  ["/apps/deliveroo/interface-utilisateur", "/apps/deliveroo/user-interface"],
  ["/apps/deliveroo/faqs/connecter-depuis-le-back-office-deliveroo", "/apps/deliveroo/faqs/connect-from-deliveroo-back-office"],
  ["/apps/deliveroo/faqs/connecter-plusieurs-restaurants-deliveroo", "/apps/deliveroo/faqs/connecting-multiple-instances-deliveroo"],
  ["/apps/deliveroo/faqs/deliveroo-sans-tablette", "/apps/deliveroo/faqs/deliveroo-tabletless"],
  ["/apps/deliveroo/faqs/trouver-mon-identifiant-de-restaurant-deliveroo", "/apps/deliveroo/faqs/find-deliveroo-restaurant-id"],
  ["/apps/dishop/connexion-hubrise", "/apps/dishop/connect-hubrise"],
  ["/apps/dishop/associer-codes-ref", "/apps/dishop/map-ref-codes"],
  ["/apps/dishop/importer-catalogue", "/apps/dishop/pull-catalog"],
  ["/apps/dishop/terminologie", "/apps/dishop/terminology"],
  ["/apps/dood/connexion-hubrise", "/apps/dood/connect-hubrise"],
  ["/apps/dood/associer-codes-ref", "/apps/dood/map-ref-codes"],
  ["/apps/dood/terminologie", "/apps/dood/terminology"],
  ["/apps/expedy/connexion-hubrise", "/apps/expedy/connect-hubrise"],
  ["/apps/expedy/details-techniques", "/apps/expedy/technical-details"],
  ["/apps/expedy/terminologie", "/apps/expedy/terminology"],
  ["/apps/expedy/interface-utilisateur", "/apps/expedy/user-interface"],
  ["/apps/expedy/faqs/conserver-mon-imprimante", "/apps/expedy/faqs/keep-my-printer"],
  ["/apps/hop-delivery/connexion-hubrise", "/apps/hop-delivery/connect-hubrise"],
  ["/apps/hop-delivery/associer-codes-ref", "/apps/hop-delivery/map-ref-codes"],
  ["/apps/hop-delivery/terminologie", "/apps/hop-delivery/terminology"],
  ["/apps/just-eat-flyt/connexion-hubrise", "/apps/just-eat-flyt/connect-hubrise"],
  ["/apps/just-eat-flyt/envoi-catalogue", "/apps/just-eat-flyt/push-catalog"],
  ["/apps/just-eat-flyt/recevoir-commandes", "/apps/just-eat-flyt/receive-orders"],
  ["/apps/just-eat-flyt/terminologie", "/apps/just-eat-flyt/terminology"],
  ["/apps/just-eat-flyt/interface-utilisateur", "/apps/just-eat-flyt/user-interface"],
  ["/apps/just-eat-flyt/faqs/auto-acceptation", "/apps/just-eat-flyt/faqs/auto-accept"],
  ["/apps/just-eat-flyt/faqs/commandes-non-envoyees", "/apps/just-eat-flyt/faqs/orders-not-sent"],
  ["/apps/just-eat-flyt/faqs/produits-non-envoyes", "/apps/just-eat-flyt/faqs/products-not-pushed"],
  ["/apps/just-eat-flyt/faqs/desactiver-tablette", "/apps/just-eat-flyt/faqs/turn-off-orderpad"],
  ["/apps/just-eat-takeaway/connexion-hubrise", "/apps/just-eat-takeaway/connect-hubrise"],
  ["/apps/just-eat-takeaway/associer-codes-ref", "/apps/just-eat-takeaway/map-ref-codes"],
  ["/apps/just-eat-takeaway/recevoir-commandes", "/apps/just-eat-takeaway/receive-orders"],
  ["/apps/just-eat-takeaway/terminologie", "/apps/just-eat-takeaway/terminology"],
  ["/apps/just-eat-takeaway/interface-utilisateur", "/apps/just-eat-takeaway/user-interface"],
  ["/apps/just-eat-takeaway/faqs/connexion-primaire-secondaire", "/apps/just-eat-takeaway/faqs/primary-secondary-connections"],
  ["/apps/kezia/connexion-hubrise", "/apps/kezia/connect-hubrise"],
  ["/apps/kezia/plateformes-livraison-repas", "/apps/kezia/food-delivery-platforms"],
  ["/apps/kezia/associer-codes-ref", "/apps/kezia/map-ref-codes"],
  ["/apps/kezia/commandes", "/apps/kezia/orders"],
  ["/apps/kezia/details-techniques", "/apps/kezia/technical-details"],
  ["/apps/kezia/terminologie", "/apps/kezia/terminology"],
  ["/apps/kezia/faqs/differences-prix", "/apps/kezia/faqs/price-differences-errors"],
  ["/apps/kezia/faqs/produit-non-exporte", "/apps/kezia/faqs/product-not-exported"],
  ["/apps/koust/connexion-hubrise", "/apps/koust/connect-hubrise"],
  ["/apps/koust/associer-codes-ref", "/apps/koust/map-ref-codes"],
  ["/apps/koust/terminologie", "/apps/koust/terminology"],
  ["/apps/koust/utilisation-sans-logiciel-caisse", "/apps/koust/usage-without-epos"],
  ["/apps/koust/interface-utilisateur", "/apps/koust/user-interface"],
  ["/apps/la-toque-magique/connexion-hubrise", "/apps/la-toque-magique/connect-hubrise"],
  ["/apps/la-toque-magique/associer-codes-ref", "/apps/la-toque-magique/map-ref-codes"],
  ["/apps/la-toque-magique/importer-catalogue", "/apps/la-toque-magique/pull-catalog"],
  ["/apps/la-toque-magique/terminologie", "/apps/la-toque-magique/terminology"],
  ["/apps/leo2/connexion-hubrise", "/apps/leo2/connect-hubrise"],
  ["/apps/leo2/plateformes-livraison-repas", "/apps/leo2/food-delivery-platforms"],
  ["/apps/leo2/associer-codes-ref", "/apps/leo2/map-ref-codes"],
  ["/apps/leo2/recevoir-commandes", "/apps/leo2/receive-orders"],
  ["/apps/leo2/terminologie", "/apps/leo2/terminology"],
  ["/apps/leo2/faqs/commandes-non-recues", "/apps/leo2/faqs/orders-not-received-errors"],
  ["/apps/lightspeed-restaurant/faqs/mettre-a-jour-lightspeed-restaurant-bridge", "/apps/lightspeed-restaurant/faqs/update-lightspeed-restaurant-bridge"],
  ["/apps/melba/connexion-hubrise", "/apps/melba/connect-hubrise"],
  ["/apps/melba/importer-catalogue", "/apps/melba/pull-catalog"],
  ["/apps/melba/importer-commandes", "/apps/melba/receive-orders"],
  ["/apps/miipos/connexion-hubrise", "/apps/miipos/connect-hubrise"],
  ["/apps/miipos/plateformes-livraison-repas", "/apps/miipos/food-delivery-platforms"],
  ["/apps/my-lemonade/connexion-hubrise", "/apps/my-lemonade/connect-hubrise"],
  ["/apps/my-lemonade/associer-codes-ref", "/apps/my-lemonade/map-ref-codes"],
  ["/apps/my-lemonade/importer-catalogue", "/apps/my-lemonade/pull-catalog"],
  ["/apps/my-lemonade/exporter-catalogue", "/apps/my-lemonade/push-catalog"],
  ["/apps/my-lemonade/envoyer-commandes", "/apps/my-lemonade/send-orders"],
  ["/apps/my-lemonade/terminologie", "/apps/my-lemonade/terminology"],
  ["/apps/nestor/connexion-hubrise", "/apps/nestor/connect-hubrise"],
  ["/apps/nestor/plateformes-livraison-repas", "/apps/nestor/food-delivery-platforms"],
  ["/apps/nestor/associer-codes-ref", "/apps/nestor/map-ref-codes"],
  ["/apps/nestor/commandes", "/apps/nestor/orders"],
  ["/apps/nestor/details-techniques", "/apps/nestor/technical-details"],
  ["/apps/nestor/terminologie", "/apps/nestor/terminology"],
  ["/apps/nestor/faqs/validation-commande-impossible", "/apps/nestor/faqs/cannot-confirm-order"],
  ["/apps/nestor/faqs/commandes-non-recues", "/apps/nestor/faqs/orders-not-received-errors"],
  ["/apps/nestor/faqs/prix-differents-articles", "/apps/nestor/faqs/product-price-differences"],
  ["/apps/nestor/faqs/synchroniser-points-vente", "/apps/nestor/faqs/synchronise-location"],
  ["/apps/nestor/faqs/produit-introuvable-hubrise", "/apps/nestor/faqs/unknown-product"],
  ["/apps/orderline/connexion-hubrise", "/apps/orderline/connect-hubrise"],
  ["/apps/orderline/lancer-orderline", "/apps/orderline/launch-orderline"],
  ["/apps/orderline/gerer-commandes", "/apps/orderline/manage-orders"],
  ["/apps/orderline/parametres", "/apps/orderline/settings"],
  ["/apps/orderline/depannage", "/apps/orderline/troubleshooting"],
  ["/apps/orderline/interface-utilisateur", "/apps/orderline/user-interface"],
  ["/apps/orderline/faqs/garder-notifications-sonores-activees", "/apps/orderline/faqs/keep-sound-notifications-enabled"],
  ["/apps/pos-helper/connexion-hubrise", "/apps/pos-helper/connect-hubrise"],
  ["/apps/pos-helper/plateformes-livraison-repas", "/apps/pos-helper/food-delivery-platforms"],
  ["/apps/restaurant-internet/connexion-hubrise", "/apps/restaurant-internet/connect-hubrise"],
  ["/apps/restaurant-internet/associer-codes-ref", "/apps/restaurant-internet/map-ref-codes"],
  ["/apps/restaurant-internet/importer-catalogue", "/apps/restaurant-internet/pull-catalog"],
  ["/apps/restaurant-internet/envoyer-commandes", "/apps/restaurant-internet/send-orders"],
  ["/apps/restaurant-internet/terminologie", "/apps/restaurant-internet/terminology"],
  ["/apps/smood/connexion-hubrise", "/apps/smood/connect-hubrise"],
  ["/apps/smood/associer-codes-ref", "/apps/smood/map-ref-codes"],
  ["/apps/smood/recuperer-catalogue", "/apps/smood/pull-catalog"],
  ["/apps/smood/envoyer-commandes", "/apps/smood/send-orders"],
  ["/apps/smood/terminologie", "/apps/smood/terminology"],
  ["/apps/smood/faqs/promotions-non-importees", "/apps/smood/faqs/deals-not-imported"],
  ["/apps/somm-it/connexion-hubrise", "/apps/somm-it/connect-hubrise"],
  ["/apps/somm-it/importer-catalogue", "/apps/somm-it/pull-catalog"],
  ["/apps/somm-it/terminologie", "/apps/somm-it/terminology"],
  ["/apps/superdigital/connexion-hubrise", "/apps/superdigital/connect-hubrise"],
  ["/apps/superdigital/associer-codes-ref", "/apps/superdigital/map-ref-codes"],
  ["/apps/superdigital/envoyer-commandes", "/apps/superdigital/send-orders"],
  ["/apps/superdigital/terminologie", "/apps/superdigital/terminology"],
  ["/apps/tickncook/connexion-hubrise", "/apps/tickncook/connect-hubrise"],
  ["/apps/tickncook/recevoir-commandes", "/apps/tickncook/receive-orders"],
  ["/apps/uber-eats/connexion-hubrise", "/apps/uber-eats/connect-hubrise"],
  ["/apps/uber-eats/associer-codes-ref", "/apps/uber-eats/map-ref-codes"],
  ["/apps/uber-eats/terminologie", "/apps/uber-eats/terminology"],
  ["/apps/uber-eats/interface-utilisateur", "/apps/uber-eats/user-interface"],
  ["/apps/uber-eats/faqs/connecter-plusieurs-restaurants-uber-eats", "/apps/uber-eats/faqs/connecting-multiple-instances-uber-eats"],
  ["/apps/uber-eats/faqs/commandes-non-recues", "/apps/uber-eats/faqs/orders-not-received-errors"],
  ["/apps/uber-eats/faqs/recevoir-commandes-sans-tablette", "/apps/uber-eats/faqs/send-orders-to-epos-without-tablet"],
  ["/apps/ultimapos/connexion-hubrise", "/apps/ultimapos/connect-hubrise"],
  ["/apps/ultimapos/plateformes-livraison-repas", "/apps/ultimapos/food-delivery-platforms"],
  ["/apps/ultimapos/associer-codes-ref", "/apps/ultimapos/map-ref-codes"],
  ["/apps/ultimapos/exporter-catalogue", "/apps/ultimapos/push-catalog"],
  ["/apps/ultimapos/exporter-inventaire", "/apps/ultimapos/push-inventory"],
  ["/apps/ultimapos/terminologie", "/apps/ultimapos/terminology"],
  ["/apps/zelty/connexion-hubrise", "/apps/zelty/connect-hubrise"],
  ["/apps/zelty/associer-codes-ref", "/apps/zelty/map-ref-codes"],
  ["/apps/zelty/commandes", "/apps/zelty/orders"],
  ["/apps/zelty/exporter-catalogue", "/apps/zelty/push-catalog"],
  ["/apps/zelty/terminologie", "/apps/zelty/terminology"],
  ["/apps/zelty/depannage", "/apps/zelty/troubleshooting"],
  ["/contributing/comment-contribuer", "/contributing/how-to-contribute"],
  ["/contributing/referencer-votre-solution-sur-hubrise", "/contributing/reference-your-solution-on-hubrise"],
  ["/contributing/guide-de-style", "/contributing/style-guide"],
  ["/docs/comptes", "/docs/account"],
  ["/docs/catalogues", "/docs/catalog"],
  ["/docs/connexions", "/docs/connections"],
  ["/docs/listes-clients", "/docs/customer-lists"],
  ["/docs/tableau-de-bord", "/docs/dashboard"],
  ["/docs/donnees", "/docs/data"],
  ["/docs/developpeur", "/docs/developer"],
  ["/docs/comment-demarrer", "/docs/get-started"],
  ["/docs/points-de-vente", "/docs/locations"],
  ["/docs/paiement", "/docs/payment"],
  ["/docs/profil-mot-de-passe", "/docs/profile-password"],
  ["/docs/utilisation-formule", "/docs/usage-plan"],
  ["/docs/faqs/create-an-account-for-another-business", "/docs/faqs/create-an-account-for-another-business-share-access"],
  ["/docs/faqs/verifier-connexion-entre-mon-systeme-et-hubrise", "/docs/faqs/check-connection-between-my-system-and-hubrise"],
  ["/docs/faqs/verifier-si-j-ai-deja-un-profil-utilisateur-dans-hubrise", "/docs/faqs/check-if-i-already-have-a-user-profile-in-hubrise"],
  ["/docs/faqs/connecter-plusieurs-fois-la-meme-application", "/docs/faqs/connect-multiple-instances-same-app"],
  ["/docs/faqs/creer-profil-utilisateur-pour-une-autre-personne", "/docs/faqs/create-a-user-profile-for-another-person"],
  ["/docs/faqs/creer-compte-pour-une-autre-entreprise", "/docs/faqs/create-an-account-for-another-business"],
  ["/docs/faqs/formule-gratuite-quota-depasse-ce-qui-se-passe", "/docs/faqs/free-plan-quota-exceeded-what-happens"],
  ["/docs/faqs/comment-effacer-des-comptes", "/docs/faqs/how-can-i-clear-accounts"],
  ["/docs/faqs/formule-interrompue-pendant-les-phases-de-configuration-et-de-test", "/docs/faqs/pause-plan-during-setup-and-test-phases"],
  ["/docs/faqs/payer-la-premiere-facture", "/docs/faqs/pay-first-invoice"],
  ["/docs/faqs/reactiver-un-compte-suspendu", "/docs/faqs/reactivate-suspended-account"],
  ["/docs/faqs/reinitialiser-mot-de-passe-hubrise-perdu", "/docs/faqs/recover-lost-password-in-hubrise"],
  ["/docs/faqs/arreter-de-payer-abonnement", "/docs/faqs/stop-paying-subscription"],
  ["/docs/hubrise-logs/un-exemple-pratique", "/docs/hubrise-logs/a-practical-example"],
  ["/docs/hubrise-logs/modele-donnees-hubrise", "/docs/hubrise-logs/hubrise-data-model"],
  ["/docs/hubrise-logs/introduction-aux-requetes-api", "/docs/hubrise-logs/introduction-to-api-requests"],
  ["/docs/hubrise-logs/requetes-json-dans-hubrise", "/docs/hubrise-logs/json-requests-in-hubrise"],
  ["/docs/hubrise-logs/organisation-informations", "/docs/hubrise-logs/organising-information"],
  ["/docs/hubrise-logs/deboguer-requetes", "/docs/hubrise-logs/troubleshooting-requests"],
  ["/docs/hubrise-logs/comprendre-syntaxe-json", "/docs/hubrise-logs/understanding-json-syntax"],
  ["/legal/conditions-generales", "/legal/general_conditions"],
  ["/legal/mentions-legales", "/legal/legal_notices"],
  ]

pathPairs.forEach((pathPair) => replacePathsInFiles(pathPair))
